# Site settings
title: Valentina Vannesluoma | Copywriter | Digimarkkinoija | Kääntäjä
description: Sisällöntuotanto, some- ja hakusanamainonta, käännökset ja oikoluku. Myös kielikoulutusta ranskassa ja espanjassa sekä suomen kielenhuollossa. Kysy lisää!
email: vmvannesluoma@gmail.com

# Build settings
markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
